export type IMetrics = {
    readonly title: number;
    readonly span: number;
    readonly tiny: number;
    readonly xxs: number;
    readonly xs: number;
    readonly small: number;
    readonly sMedium: number;
    readonly medium: number;
    readonly large: number;
    readonly xl: number;
    readonly xxl: number;
    readonly xxxl: number;
    readonly huge: number;
    readonly massive: number;
    readonly giant: number;
    readonly borderRadius: number;
    readonly borderRadiusLarge: number;
    readonly borderRadiusHuge: number;
    readonly marginTop: number;
    readonly marginHorizontal: number;
    readonly marginVertical: number;
    readonly paddingHorizontal: number;
    readonly voucherBorderRadius: number;
    readonly logoWidth: number;
    readonly logoHeight: number;
    readonly icon: number;
};
export type IHitSlop = {
    readonly top: number;
    readonly bottom: number;
    readonly right: number;
    readonly left: number;
};
declare const hitSlop: IHitSlop;
declare const responsiveFont: <T extends number>(value: T) => T;
declare const deviceWidth: () => number;
declare const deviceHeight: () => number;
declare const responsiveWidth: <T extends number>(value: T) => T;
declare const responsiveHeight: <T extends number>(value: T) => T;
export type IActiveOpacity = {
    readonly none: number;
    readonly low: number;
    readonly medium: number;
    readonly high: number;
    readonly veryHigh: number;
};
declare const activeOpacity: IActiveOpacity;
declare const isIOS: boolean;
declare const metrics: {
    readonly title: 20;
    readonly span: 14;
    readonly line: 1;
    readonly tiny: 4;
    readonly xxs: 8;
    readonly xs: 12;
    readonly small: 16;
    readonly sMedium: 18;
    readonly medium: 20;
    readonly large: 24;
    readonly xl: 28;
    readonly xxl: 32;
    readonly xxxl: 40;
    readonly huge: 48;
    readonly massive: 64;
    readonly giant: 80;
    readonly borderRadius: 5;
    readonly borderRadiusLarge: 10;
    readonly borderRadiusHuge: 20;
    readonly marginTop: 12;
    readonly marginHorizontal: 24;
    readonly marginVertical: 16;
    readonly paddingHorizontal: 20;
    readonly voucherBorderRadius: 15;
    readonly logoWidth: 300;
    readonly logoHeight: 70;
    readonly icon: 30;
};
export { metrics, isIOS, hitSlop, activeOpacity, responsiveFont, responsiveHeight, responsiveWidth, deviceWidth, deviceHeight, };
//# sourceMappingURL=metrics.d.ts.map