name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        dir=$(yarn cache dir)
        echo "YARN_CACHE_DIR=$dir" >> $GITHUB_ENV
      shell: bash
    # Note that the cache is unique to the runner
    - name: Restore node_modules from cache
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile --network-timeout 300000
      shell: bash
