import type { ColorModeOptions } from '../core/color-mode/type';
declare const darkColors: {
    backgroundPrimary: string;
    primary: string;
    secondary: string;
    tertiary: string;
    danger: string;
    error: string;
    success: string;
    warning: string;
    muted: string;
    info: string;
    light: string;
    white: string;
    black: string;
    darkText: string;
    rose: string;
    pink: string;
    fuchsia: string;
    purple: string;
    violet: string;
    indigo: string;
    blue: string;
    lightBlue: string;
    darkBlue: string;
    cyan: string;
    teal: string;
    emerald: string;
    green: string;
    lime: string;
    yellow: string;
    amber: string;
    orange: string;
    red: string;
    warmGray: string;
    trueGray: string;
    gray: string;
    coolGray: string;
    blueGray: string;
    dark: string;
    transparent: string;
    lightBackground: string;
    backgroundSecondary: string;
    mainBackground: string;
    cardPrimaryBackground: string;
    primaryBorder: string;
    textColor: string;
    cardBackground: string;
    lightTextColor: string;
    darkTextColor: string;
    placeHolderText: string;
    errorText: string;
};
declare const theme: {
    components: {
        Button: import("./components/Button").ButtonThemeProps;
        ButtonOutline: import("./components/Button").ButtonThemeProps;
        ButtonPrimary: import("./components/Button").ButtonThemeProps;
        ButtonSecondary: import("./components/Button").ButtonThemeProps;
        ButtonTransparent: import("./components/Button").ButtonThemeProps;
        Checkbox: import("./components/Checkbox").CheckboxThemeProps;
        Text: import("./components/Text").TextThemeProps;
    };
    config: ColorModeOptions;
    darkColors: {
        backgroundPrimary: string;
        primary: string;
        secondary: string;
        tertiary: string;
        danger: string;
        error: string;
        success: string;
        warning: string;
        muted: string;
        info: string;
        light: string;
        white: string;
        black: string;
        darkText: string;
        rose: string;
        pink: string;
        fuchsia: string;
        purple: string;
        violet: string;
        indigo: string;
        blue: string;
        lightBlue: string;
        darkBlue: string;
        cyan: string;
        teal: string;
        emerald: string;
        green: string;
        lime: string;
        yellow: string;
        amber: string;
        orange: string;
        red: string;
        warmGray: string;
        trueGray: string;
        gray: string;
        coolGray: string;
        blueGray: string;
        dark: string;
        transparent: string;
        lightBackground: string;
        backgroundSecondary: string;
        mainBackground: string;
        cardPrimaryBackground: string;
        primaryBorder: string;
        textColor: string;
        cardBackground: string;
        lightTextColor: string;
        darkTextColor: string;
        placeHolderText: string;
        errorText: string;
    };
    fontWeights: {
        hairline: number;
        thin: number;
        light: number;
        normal: number;
        medium: number;
        semibold: number;
        bold: number;
        extrabold: number;
        black: number;
        extraBlack: number;
    };
    fonts: {
        heading: undefined;
        body: undefined;
        mono: undefined;
        regular: string | undefined;
        bold: string | undefined;
        italic: string | undefined;
    };
    fontSizes: {
        '2xs': number;
        xs: number;
        sm: number;
        md: number;
        lg: number;
        xl: number;
        '2xl': number;
        '3xl': number;
        '4xl': number;
        '5xl': number;
        '6xl': number;
        '7xl': number;
        '8xl': number;
        '9xl': number;
    };
    colors: {
        backgroundPrimary: string;
        primary: string;
        secondary: string;
        tertiary: string;
        danger: string;
        error: string;
        success: string;
        warning: string;
        muted: string;
        info: string;
        light: string;
        white: string;
        black: string;
        darkText: string;
        rose: string;
        pink: string;
        fuchsia: string;
        purple: string;
        violet: string;
        indigo: string;
        blue: string;
        lightBlue: string;
        darkBlue: string;
        cyan: string;
        teal: string;
        emerald: string;
        green: string;
        lime: string;
        yellow: string;
        amber: string;
        orange: string;
        red: string;
        warmGray: string;
        trueGray: string;
        gray: string;
        coolGray: string;
        blueGray: string;
        dark: string;
        transparent: string;
        lightBackground: string;
        backgroundSecondary: string;
        mainBackground: string;
        cardPrimaryBackground: string;
        primaryBorder: string;
        textColor: string;
        cardBackground: string;
        lightTextColor: string;
        darkTextColor: string;
        placeHolderText: string;
        errorText: string;
    };
    borderWidths: {
        tiny: number;
        miniature: number;
        petite: number;
        small: number;
        little: number;
        compact: number;
        narrow: number;
        slim: number;
        moderate: number;
        average: number;
        substantial: number;
        large: number;
        big: number;
        grand: number;
        huge: number;
        giant: number;
        colossal: number;
        enormous: number;
        mammoth: number;
        titanic: number;
    };
    sizes: {
        tiny: number;
        miniature: number;
        petite: number;
        small: number;
        little: number;
        compact: number;
        narrow: number;
        slim: number;
        moderate: number;
        average: number;
        substantial: number;
        large: number;
        big: number;
        grand: number;
        huge: number;
        giant: number;
        colossal: number;
        enormous: number;
        mammoth: number;
        titanic: number;
    };
    spacing: {
        tiny: number;
        miniature: number;
        petite: number;
        small: number;
        little: number;
        compact: number;
        narrow: number;
        slim: number;
        moderate: number;
        average: number;
        substantial: number;
        large: number;
        big: number;
        grand: number;
        huge: number;
        giant: number;
        colossal: number;
        enormous: number;
        mammoth: number;
        titanic: number;
        gigantic: number;
    };
    opacity: {
        transparent: number;
        translucent: number;
        hazy: number;
        misty: number;
        faint: number;
        lightyOpaque: number;
        semiOpaque: number;
        partiallyOpaque: number;
        clouded: number;
        murky: number;
        opaque: number;
        solid: number;
        dense: number;
        darkened: number;
        blackened: number;
    };
    shadows: {
        tiny: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        miniature: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        petite: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        small: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        little: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        compact: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        narrow: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        slim: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        moderate: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
        average: {
            shadowColor: string;
            shadowOffset: {
                width: number;
                height: number;
            };
            shadowOpacity: number;
            shadowRadius: number;
            elevation: number;
        };
    };
};
type Theme = typeof theme;
type DarkColors = typeof darkColors;
type IColors = typeof theme.colors;
interface ICustomTheme {
}
interface ITheme extends ICustomTheme, Omit<Theme, keyof ICustomTheme> {
}
export { theme, Theme, ITheme, ICustomTheme, DarkColors, IColors };
//# sourceMappingURL=theme.d.ts.map