const DURATION = 200
const FOCUSED = 1
const OUT_OF_FOCUS = 0
const BLURRED = 1
const OUT_OF_BLUR = 0
const DEFAULT_WIDTH = 0
const DEFAULT_HEIGHT = 0
const FOCUSED_FONTSIZE = 11
const UNFOCUSED_FONTSIZE = 14

export {
  DURATION,
  FOCUSED,
  OUT_OF_BLUR,
  OUT_OF_FOCUS,
  BLURRED,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  FOCUSED_FONTSIZE,
  UNFOCUSED_FONTSIZE,
}
