const DEFAULT_STEP = 1;
const INIT_POINT = 0;
const MINIMUM_TRACK_WIDTH = 0;
const DEFAULT_MINIMUM_VALUE = 0;
const DEFAULT_MAXIMUM_VALUE = 1;
const INIT_VALUE = 0;
const VISIBLE = 1;
const INVISIBLE = 0;
const NEXT_STEP = 1;
const PREVIOUS_STEP = 1;
const FIRST_POINT = 1;
const DURATION = 200;
const THUMB_POSITION = {
  left: 'left',
  right: 'right'
};
export { DEFAULT_MINIMUM_VALUE, DEFAULT_MAXIMUM_VALUE, DEFAULT_STEP, INIT_POINT, FIRST_POINT, MINIMUM_TRACK_WIDTH, THUMB_POSITION, INIT_VALUE, VISIBLE, INVISIBLE, NEXT_STEP, PREVIOUS_STEP, DURATION };
//# sourceMappingURL=constants.js.map