import React from 'react'
import DatePicker from 'react-native-date-picker'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DatePicker,
  'https://www.figma.com/design/JfmuXTpcFBa0xj3JzwNtxx/Saigon-Technology_MobilePortal?node-id=924-13429&m=dev',
  {
    props: {},
    example: props => <DatePicker mode="date" date={new Date()} {...props} />,
  },
)
