name: Validate changes against develop
on:
  pull_request:
    branches: ['develop']

jobs:
  linting-typechecking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Setup Project and Cache
        uses: ./.github/actions/setup

      - name: Linting, Typechecking
        run: yarn lint

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup
#        uses: ./.github/actions/setup
#
#      - name: Run unit tests
#        run: yarn test --maxWorkers=2 --coverage
